package brucehan.auth.config.exception;

public enum ApplicationExceptionType {
    OIDC_PUBLIC_KEY_NOT_FOUND,
    OIDC_PUBLIC_KEY_GENERATION_ERROR,
    JWT_EXPIRED,
    JWT_SUPPORTED,
    JWT_MALFORMED,
    JWT_INVALID_SIGNATURE,
    JWT_INVALID_FORMAT,
    JWT_VERIFICATION_FAILED,
    JWT_REFRESH_INVALID,
    JWT_REFRESH_NOT_FOUND_IN_REDIS,
    UNDEFINED_EXCEPTION
}
